C-sharp Project/Controllers/MuziekController.cs
using C_sharp_Project.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace C_sharp_Project.Controllers
{
    public class MuziekController : Controller
    {
        protected DataSet ds;
        private void DatasetInit()
        {
            ds = new DataSet("music");

            DataTable dtSongs = new DataTable("number");

            DataColumn dcId = new DataColumn("id");
            DataColumn dcArtist = new DataColumn("artist");
            DataColumn dcTitle = new DataColumn("title");
            DataColumn dcYear = new DataColumn("year");
            DataColumn dcGenre = new DataColumn("genre");
            DataColumn dcFile = new DataColumn("file");



            ds.Tables.Add(dtSongs);
            dtSongs.Columns.Add(dcId);
            dtSongs.Columns.Add(dcArtist);
            dtSongs.Columns.Add(dcTitle);
            dtSongs.Columns.Add(dcYear);
            dtSongs.Columns.Add(dcGenre);
            dtSongs.Columns.Add(dcFile);

            ds.ReadXml(Server.MapPath(@"~/App_Data/XMLFile1.xml"));

            Session["xmlDataSet"] = ds;

        }
        // GET: Muziek
        public ActionResult Index()
        {
            DatasetInit();
            List<Song> liedjes = new List<Song>();
            SongBuilder sb = new SongBuilder();


            foreach (DataRow dr in ds.Tables[0].Rows)
            {

                Song s = sb.CreateSong(dr);
                liedjes.Add(s);
            }


            return View(liedjes);
        }
        public ActionResult Create()
        {
            DatasetInit();
            return View();
        }
        public ActionResult Delete()
        {
            DatasetInit();
            return View();
        }
        public ActionResult Wijzig()
        {
            DatasetInit();
            return View();
        }
    }
}

C-sharp Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default    navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("XML", "Index", "Muziek/Index", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Toevoegen", "Create", "Muziek")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
 <style type="text/css">
     #Footer{
        position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 1rem;
    background-color: #efefef;
    text-align: center;
     }
 </style>
    </div>

     
    
    <div id="Footer">
        <footer>
            <p>&copy; @DateTime.Now.Year - Safwaan & Yannick</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>